


```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(ggthemes))
suppressMessages(library(lubridate))
suppressMessages(library(readxl))
suppressMessages(library(ggplot2))
```



sample data
```{r}
df <- read_excel("Data/rawdata.xlsx")
```

ggplot
```{r}
title<-"INMAR INTELLIGENCE"
subtitle<-"SUBTITLE"

graph<-ggplot(df, aes(x=Date, y = Value, color = Category)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  scale_color_manual(values=c("#CC6666", "#9999CC", "#D34821", "#F15894")) +
  ggtitle(label = title, 
          subtitle = subtitle) +
  theme(panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.25, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                      colour = "white"), 
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                      colour = "white"),
        text = element_text(size = 10),
        plot.title = element_text(size = 20, 
                                  color = "darkblue", 
                                  margin = margin(t = 20, r = 20, b = 0, l = 0),
                                  face = "bold"),
        plot.subtitle = element_text( size = 16, 
                                      color = "darkgreen", 
                                      margin = margin(t = 0, r = 20, b = 0, l = 0),
                                      face = "bold"),
        axis.text.x = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.text.y = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(size = 16, margin = margin(t = 20, r = 20, b = 10, l = 10)),
        axis.title.y = element_text(size = 16, margin = margin(t = 10, r = 20, b = 10, l = 10))) +
        scale_y_continuous(limits = c(0,50) )
  
  
  

print(graph)
```


